import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// --- Types ---

interface PluginAuthor {
  name: string;
  email: string;
}

interface PluginSource {
  source: string;
  repo: string;
  ref: string;
}

interface Plugin {
  name: string;
  source: PluginSource;
  description: string;
  version: string;
  category: string;
  homepage?: string;
  author?: PluginAuthor;
  tags: string[];
}

interface Marketplace {
  name: string;
  description: string;
  owner: {
    name: string;
    email: string;
    url: string;
  };
  plugins: Plugin[];
}

interface CheckResult {
  plugin: string;
  repo: string;
  currentVersion: string;
  latestVersion: string | null;
  status: "up-to-date" | "outdated" | "error" | "skipped";
  message?: string;
}

// --- Constants ---

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = resolve(__dirname, "..");
const MARKETPLACE_PATH = resolve(ROOT_DIR, ".claude-plugin", "marketplace.json");
const README_PATH = resolve(ROOT_DIR, "README.md");

const PLUGINS_START_MARKER = "<!-- AUTOGENERATED:PLUGINS:START -->";
const PLUGINS_END_MARKER = "<!-- AUTOGENERATED:PLUGINS:END -->";

// --- Helpers ---

function stripVPrefix(tag: string): string {
  return tag.replace(/^v/i, "");
}

function ensureVPrefix(version: string): string {
  return version.startsWith("v") ? version : `v${version}`;
}

function parseSemver(version: string): number[] {
  return stripVPrefix(version).split(".").map(Number);
}

/** Returns positive if a > b, negative if a < b, 0 if equal. */
function compareSemver(a: string, b: string): number {
  const pa = parseSemver(a);
  const pb = parseSemver(b);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (diff !== 0) return diff;
  }
  return 0;
}

function isValidSemver(version: string): boolean {
  return /^\d+\.\d+\.\d+$/.test(stripVPrefix(version));
}

function isValidGitHubRepo(repo: string): boolean {
  return /^[a-zA-Z0-9._-]+\/[a-zA-Z0-9._-]+$/.test(repo);
}

function checkGhCli(): void {
  try {
    execFileSync("gh", ["auth", "status"], { stdio: "pipe", encoding: "utf-8" });
  } catch {
    console.error("[ERROR] gh CLI is not installed or not authenticated.");
    console.error("        Install: https://cli.github.com/");
    console.error("        Auth:    gh auth login");
    process.exit(2);
  }
}

function fetchLatestRelease(repo: string): string | null {
  try {
    const tag = execFileSync(
      "gh",
      ["api", `repos/${repo}/releases/latest`, "--jq", ".tag_name"],
      { encoding: "utf-8", timeout: 30_000, stdio: ["pipe", "pipe", "pipe"] }
    ).trim();
    return tag || null;
  } catch {
    return null;
  }
}

// --- Validation ---

function validateMarketplace(data: unknown): data is Marketplace {
  if (typeof data !== "object" || data === null) return false;
  const m = data as Record<string, unknown>;
  if (typeof m.name !== "string") return false;
  if (!Array.isArray(m.plugins)) return false;
  for (const entry of m.plugins) {
    if (typeof entry !== "object" || entry === null) return false;
    const p = entry as Record<string, unknown>;
    if (typeof p.name !== "string") return false;
    if (typeof p.version !== "string") return false;
    if (typeof p.description !== "string") return false;
    if (typeof p.category !== "string") return false;
    if (!Array.isArray(p.tags)) return false;
    if (typeof p.source !== "object" || p.source === null) return false;
    const src = p.source as Record<string, unknown>;
    if (typeof src.source !== "string") return false;
    if (src.source === "github") {
      if (typeof src.repo !== "string") return false;
      if (typeof src.ref !== "string") return false;
    }
  }
  return true;
}

// --- Core Logic ---

function checkPlugins(marketplace: Marketplace): CheckResult[] {
  const results: CheckResult[] = [];

  for (const plugin of marketplace.plugins) {
    if (plugin.source.source !== "github") {
      results.push({
        plugin: plugin.name,
        repo: "",
        currentVersion: plugin.version,
        latestVersion: null,
        status: "skipped",
        message: "non-GitHub source",
      });
      continue;
    }

    if (!isValidGitHubRepo(plugin.source.repo)) {
      results.push({
        plugin: plugin.name,
        repo: plugin.source.repo,
        currentVersion: plugin.version,
        latestVersion: null,
        status: "error",
        message: `invalid repo format: ${plugin.source.repo}`,
      });
      continue;
    }

    const latestTag = fetchLatestRelease(plugin.source.repo);
    if (!latestTag) {
      results.push({
        plugin: plugin.name,
        repo: plugin.source.repo,
        currentVersion: plugin.version,
        latestVersion: null,
        status: "error",
        message: `no stable release found for ${plugin.source.repo}`,
      });
      continue;
    }

    if (!isValidSemver(latestTag)) {
      results.push({
        plugin: plugin.name,
        repo: plugin.source.repo,
        currentVersion: plugin.version,
        latestVersion: stripVPrefix(latestTag),
        status: "error",
        message: `latest release tag "${latestTag}" is not valid semver`,
      });
      continue;
    }

    const latestVersion = stripVPrefix(latestTag);
    const comparison = compareSemver(latestVersion, plugin.version);

    if (comparison === 0) {
      results.push({
        plugin: plugin.name,
        repo: plugin.source.repo,
        currentVersion: plugin.version,
        latestVersion,
        status: "up-to-date",
      });
    } else if (comparison > 0) {
      results.push({
        plugin: plugin.name,
        repo: plugin.source.repo,
        currentVersion: plugin.version,
        latestVersion,
        status: "outdated",
      });
    } else {
      // Current version is newer than latest stable release (e.g., pinned to pre-release)
      results.push({
        plugin: plugin.name,
        repo: plugin.source.repo,
        currentVersion: plugin.version,
        latestVersion,
        status: "up-to-date",
        message: `pinned ahead of latest stable (v${latestVersion})`,
      });
    }
  }

  return results;
}

function applyUpdates(marketplace: Marketplace, results: CheckResult[]): boolean {
  let changed = false;

  for (const result of results) {
    if (result.status !== "outdated" || !result.latestVersion) continue;

    const plugin = marketplace.plugins.find((p) => p.name === result.plugin);
    if (!plugin) continue;

    plugin.version = result.latestVersion;
    plugin.source.ref = ensureVPrefix(result.latestVersion);
    changed = true;
  }

  if (changed) {
    writeFileSync(MARKETPLACE_PATH, JSON.stringify(marketplace, null, 2) + "\n");
  }

  return changed;
}

function generatePluginSection(marketplace: Marketplace): string {
  // Group plugins by category
  const byCategory = new Map<string, Plugin[]>();
  for (const p of marketplace.plugins) {
    const cat = p.category || "other";
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(p);
  }

  const sections: string[] = [];
  for (const [category, plugins] of byCategory) {
    const heading = `### ${category.charAt(0).toUpperCase() + category.slice(1)}`;
    const rows = plugins.map((p) => {
      const repoUrl =
        p.homepage ||
        (p.source.source === "github"
          ? `https://github.com/${p.source.repo}`
          : "");
      const nameCell = repoUrl
        ? `**[${p.name}](${repoUrl})**`
        : `**${p.name}**`;
      const desc = p.description.replace(/\|/g, "\\|");
      return `| ${nameCell} | v${p.version} | ${desc} |`;
    });

    sections.push(
      [
        heading,
        "",
        "| Plugin | Version | Description |",
        "|--------|---------|-------------|",
        ...rows,
      ].join("\n")
    );
  }

  return sections.join("\n\n");
}

function updateReadme(marketplace: Marketplace): "updated" | "unchanged" | "error" {
  let readme: string;
  try {
    readme = readFileSync(README_PATH, "utf-8");
  } catch {
    console.error("[ERROR] README.md not found at", README_PATH);
    return "error";
  }

  const startIdx = readme.indexOf(PLUGINS_START_MARKER);
  const endIdx = readme.indexOf(PLUGINS_END_MARKER);

  if (startIdx === -1 || endIdx === -1) {
    console.error("[ERROR] README.md is missing autogeneration markers.");
    console.error(`        Expected: ${PLUGINS_START_MARKER}`);
    console.error(`        Expected: ${PLUGINS_END_MARKER}`);
    return "error";
  }

  const before = readme.slice(0, startIdx + PLUGINS_START_MARKER.length);
  const after = readme.slice(endIdx);
  const pluginSection = generatePluginSection(marketplace);

  const updated = `${before}\n\n${pluginSection}\n\n${after}`;

  if (updated === readme) return "unchanged";

  writeFileSync(README_PATH, updated);
  return "updated";
}

// --- Reporting ---

function printResults(results: CheckResult[]): void {
  for (const r of results) {
    switch (r.status) {
      case "up-to-date":
        if (r.message) {
          console.log(`  [OK]       ${r.plugin} (v${r.currentVersion}) -- ${r.message}`);
        } else {
          console.log(`  [OK]       ${r.plugin} (v${r.currentVersion}) -- up to date`);
        }
        break;
      case "outdated":
        console.log(
          `  [OUTDATED] ${r.plugin} (v${r.currentVersion} -> v${r.latestVersion}) -- update available`
        );
        break;
      case "error":
        console.log(`  [WARN]     ${r.plugin} -- ${r.message}`);
        break;
      case "skipped":
        console.log(`  [SKIP]     ${r.plugin} -- ${r.message}`);
        break;
    }
  }
}

function printUpdateSummary(results: CheckResult[], readmeStatus: "updated" | "unchanged" | "error"): void {
  const outdated = results.filter((r) => r.status === "outdated");
  console.log("\nUpdated plugins:");
  for (const r of outdated) {
    console.log(`  ${r.plugin}: v${r.currentVersion} -> v${r.latestVersion}`);
  }
  console.log("\nFiles updated:");
  console.log("  - .claude-plugin/marketplace.json");
  if (readmeStatus === "updated") {
    console.log("  - README.md");
  }
}

// --- Main ---

function main(): void {
  const args = process.argv.slice(2);
  const shouldUpdate = args.includes("--update");

  console.log("AIDA Marketplace - Plugin Version Checker\n");

  checkGhCli();

  let raw: string;
  try {
    raw = readFileSync(MARKETPLACE_PATH, "utf-8");
  } catch {
    console.error("[ERROR] marketplace.json not found at", MARKETPLACE_PATH);
    process.exit(2);
    return;
  }

  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch {
    console.error("[ERROR] Failed to parse marketplace.json");
    process.exit(2);
    return;
  }

  if (!validateMarketplace(data)) {
    console.error("[ERROR] marketplace.json has invalid structure.");
    console.error("        Ensure it has 'name', 'plugins' array, and each plugin has");
    console.error("        'name', 'version', 'description', and 'source' fields.");
    process.exit(2);
    return;
  }

  const marketplace = data;

  console.log(`Checking ${marketplace.plugins.length} plugin(s)...\n`);

  const results = checkPlugins(marketplace);
  printResults(results);

  const hasErrors = results.some((r) => r.status === "error");
  const hasOutdated = results.some((r) => r.status === "outdated");

  console.log();

  // Always warn about errors, even when outdated plugins also exist
  if (hasErrors) {
    console.log("WARNING: Some plugins could not be checked. See warnings above.\n");
  }

  if (!hasOutdated) {
    console.log("All plugins are up to date.");
    process.exit(hasErrors ? 2 : 0);
    return;
  }

  if (!shouldUpdate) {
    console.log("Updates available. Run with --update to apply.");
    process.exit(1);
    return;
  }

  // Apply updates.
  // Note: applyUpdates mutates the marketplace object in place.
  // updateReadme must be called after so it generates content with the new versions.
  console.log("Applying updates...\n");

  const didUpdate = applyUpdates(marketplace, results);
  if (!didUpdate) {
    console.log("[WARN] No changes were applied despite outdated plugins being detected.");
    process.exit(2);
    return;
  }

  const readmeStatus = updateReadme(marketplace);

  switch (readmeStatus) {
    case "error":
      console.log("[WARN] README.md could not be updated. Add autogeneration markers.");
      break;
    case "unchanged":
      console.log("README.md already up to date.");
      break;
    case "updated":
      console.log("README.md updated.");
      break;
  }

  printUpdateSummary(results, readmeStatus);
  process.exit(0);
}

main();
